# Generated by Django 3.2.8 on 2021-11-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='avator',
            new_name='avatar',
        ),
    ]
